#!/bin/sh
# To enable this hook, move this file in your .git/hooks/

BUILD_NUMBER=$((`git log master --pretty=oneline | wc -l` + 1))
sed -E -i -e "{s/(build.+) ([0-9]+)/\1 $BUILD_NUMBER/};" package.json
git add package.json